name: Release

on:
  release:
    types:
      - published
      - released
jobs:
  build:
    env:
      DOCKER_REPOSITORY: ghcr.io
      IMAGE: dmc_auth
    name: Build and push
    runs-on: ubuntu-latest
    # needs: [test]
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - uses: FranzDiebold/github-env-vars-action@v2
      # Build the Docker image
      - name: Build
        run: docker build -t $DOCKER_REPOSITORY/$GITHUB_REPOSITORY/$IMAGE:${GITHUB_REF##*/} .
      - name: Login docker repository
        run: docker login $DOCKER_REPOSITORY -u $GITHUB_ACTOR --password ${{secrets.GITHUB_TOKEN}}
      - name: Publish
        run: docker push $DOCKER_REPOSITORY/$CI_REPOSITORY_OWNER/$IMAGE:${CI_ACTION_REF_NAME##*/}
